### ISSUE TITLE
Trader-Thumbnail for Desktop-View

### ISSUE THREAD

**Issue by christianaschoff** [lokalkauf/lokalkauf-functions#18]
When generating a thumbnail of an image we need a intermediate size for dektop view.

Generate new thumbnail sizes for already existing images

**Comment by buecheko** [comment]
What size should this new thumbnail be? Currently we are creating one of the size 200x200.

**Comment by christianaschoff** [comment]
the desired size is 224x224. 

Right now the larger side of the image is scaled to 200px and the smaller side is scaled accordingly to preserve aspect ratio. That is fine, but we have a lot of images that endup having a size of 133x200. That is being upscaled to 224x358 (or so).

We need the smaller side of the image to match the desired size.

**Comment by buecheko** [comment]
Okay. This is not possible withe the resize extension we are using. I will replace the extension with a function. This might also solve the Problem described here #6

**Comment by christianaschoff** [comment]
nice!!
