### ISSUE TITLE
"Copy Deiner Anfrage" in mail subject.

### ISSUE THREAD

**Issue by d0ntrash** [lokalkauf/lokalkauf-functions#31]
After sending a request to a trader the subject of the confirmation mail to the sender looks like that: "Copy Deiner Anfrage" 

"Kopie Deiner Anfrage" would probably be better.

**Comment by christianaschoff** [comment]
@JnSnw : this has to be changed within the snedgrid template.
I do not have access to that.
Can you fix that issue, please?

**Comment by DekuEdamame** [comment]
Changed Copy to Kopie in Sendgrid.

**Comment by Dipanjana1990** [comment]
tested and is Okay
![image](https://user-images.githubusercontent.com/68644410/112874084-c6e6c600-90c2-11eb-9c1a-b9424723b0f6.png)
