### ISSUE TITLE
Thumbnail generation with certain images

### ISSUE THREAD

**Issue by christianaschoff** [lokalkauf/lokalkauf-functions#6]
Some images are not properly reduced to a thumbnail size. Thumbnail image is empty after upload. Fullsize image is displayed correctly.

**Comment by buecheko** [comment]
Can you send me some of those pictures?

**Comment by christianaschoff** [comment]
same image as in trello

**Comment by buecheko** [comment]
The image seems to be uploaded and resized correctly. But the frontend doesn't seem to get a download link back for the image.
