### ISSUE TITLE
Password-Reset-Link leads to .firebaseapp.com domain.

### ISSUE THREAD

**Issue by christianaschoff** [lokalkauf/lokalkauf-functions#8]
Password Reset works, but I can not login with now password until I reload the page manually with web.app domain.
Until then the page states that my account is not valid (?)

Same issue like Stefan had - see Testplan-Release-4 document for details.

**Comment by buecheko** [comment]
Problem should be solved. Can anyone verify that? @kleste @christianaschoff 
I have changed the URL in the mail template of Firebase and in the server variables.
